package Clases;
// Generated 18 mar 2024 17:03:38 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente")
public class Cliente implements java.io.Serializable {
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="id")
	private Integer id;
	@Column(name="nombre_usuario")
	private String nombreUsuario;
	@Column(name="domicilio")
	private String domicilio;
	@Column(name="telefono")
	private String telefono;
	@Column(name="correo")
	private String correo;
	@OneToMany(mappedBy="cliente", targetEntity=Juego.class)
	private Set juegos = new HashSet(0);

	public Cliente() {
	}

	public Cliente(String nombreUsuario, String domicilio, String telefono, String correo, Set juegos) {
		this.nombreUsuario = nombreUsuario;
		this.domicilio = domicilio;
		this.telefono = telefono;
		this.correo = correo;
		this.juegos = juegos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public Set getJuegos() {
		return this.juegos;
	}

	public void setJuegos(Set juegos) {
		this.juegos = juegos;
	}

}
