package Clases;
// Generated 25 mar 2024 23:14:46 by Hibernate Tools 6.3.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Compannia generated by hbm2java
 */
@Entity
@Table(name="compannia")
public class Compannia implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="id")
	private int id;
	@Column(name="nombre")
	private String nombre;
	@Column(name="anno_de_fundacion")
	private Date annoDeFundacion;
	@OneToMany(mappedBy="compannia", targetEntity=Juego.class)
	private Set juegos = new HashSet(0);

	public Compannia() {
	}

	public Compannia(String nombre, Date annoDeFundacion) {
		this.nombre = nombre;
		this.annoDeFundacion = annoDeFundacion;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getAnnoDeFundacion() {
		return this.annoDeFundacion;
	}

	public void setAnnoDeFundacion(Date annoDeFundacion) {
		this.annoDeFundacion = annoDeFundacion;
	}

	public Set getJuegos() {
		return this.juegos;
	}

	public void setJuegos(Set juegos) {
		this.juegos = juegos;
	}

}
