package Clases;
// Generated 25 mar 2024 23:14:46 by Hibernate Tools 6.3.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compannia generated by hbm2java
 */
public class Compannia implements java.io.Serializable {

	private int id;
	private String nombre;
	private Date annoDeFundacion;
	private Set juegos = new HashSet(0);

	public Compannia() {
	}

	public Compannia(int id, String nombre, Date annoDeFundacion, Set juegos) {
		this.id = id;
		this.nombre = nombre;
		this.annoDeFundacion = annoDeFundacion;
		this.juegos = juegos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getAnnoDeFundacion() {
		return this.annoDeFundacion;
	}

	public void setAnnoDeFundacion(Date annoDeFundacion) {
		this.annoDeFundacion = annoDeFundacion;
	}

	public Set getJuegos() {
		return this.juegos;
	}

	public void setJuegos(Set juegos) {
		this.juegos = juegos;
	}

}
