package Clases;
// Generated 27 mar 2024 16:53:23 by Hibernate Tools 6.3.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Consola generated by hbm2java
 */
@Entity
@Table(name="consola")
public class Consola implements java.io.Serializable {
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="id")
	private int id;
	@Column(name="nombre")
	private String nombre;
	@Column(name="anno_salida")
	private Date annoSalida;
	@ManyToMany(mappedBy = "consolas")
	private Set<Juego> juegos = new HashSet<>();

	public Consola() {
	}

	public Consola(String nombre, Date annoSalida, Set juegos) {
		this.nombre = nombre;
		this.annoSalida = annoSalida;
		this.juegos = juegos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getAnnoSalida() {
		return this.annoSalida;
	}

	public void setAnnoSalida(Date annoSalida) {
		this.annoSalida = annoSalida;
	}

	public Set<Juego> getJuegos() {
		return this.juegos;
	}

	public void setJuegos(Set<Juego> juegos) {
		this.juegos = juegos;
	}
	
}
