package Clases;
// Generated 25 mar 2024 23:14:46 by Hibernate Tools 6.3.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Consola generated by hbm2java
 */
public class Consola implements java.io.Serializable {

	private int id;
	private String nombre;
	private Date annoSalida;
	private Set juegos = new HashSet(0);

	public Consola() {
	}

	public Consola(int id, String nombre, Date annoSalida, Set juegos) {
		this.id = id;
		this.nombre = nombre;
		this.annoSalida = annoSalida;
		this.juegos = juegos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getAnnoSalida() {
		return this.annoSalida;
	}

	public void setAnnoSalida(Date annoSalida) {
		this.annoSalida = annoSalida;
	}

	public Set getJuegos() {
		return this.juegos;
	}

	public void setJuegos(Set juegos) {
		this.juegos = juegos;
	}

}
