package Clases;
// Generated 25 mar 2024 23:14:46 by Hibernate Tools 6.3.1.Final

import java.math.BigDecimal;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Juego generated by hbm2java
 */
public class Juego implements java.io.Serializable {

	private int id;
	private Compannia compannia;
	private String nombre;
	private BigDecimal precio;
	private Date annoDeSalida;
	private Integer stock;
	private Double descuento;
	private byte[] imagen;
	private Set usuarios = new HashSet(0);
	private Set consolas = new HashSet(0);

	public Juego() {
	}

	public Juego(int id, Compannia compannia, String nombre, BigDecimal precio, Date annoDeSalida, Integer stock,
			Double descuento, byte[] imagen, Set usuarios, Set consolas) {
		this.id = id;
		this.compannia = compannia;
		this.nombre = nombre;
		this.precio = precio;
		this.annoDeSalida = annoDeSalida;
		this.stock = stock;
		this.descuento = descuento;
		this.imagen = imagen;
		this.usuarios = usuarios;
		this.consolas = consolas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Compannia getCompannia() {
		return this.compannia;
	}

	public void setCompannia(Compannia compannia) {
		this.compannia = compannia;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public Date getAnnoDeSalida() {
		return this.annoDeSalida;
	}

	public void setAnnoDeSalida(Date annoDeSalida) {
		this.annoDeSalida = annoDeSalida;
	}

	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public Double getDescuento() {
		return this.descuento;
	}

	public void setDescuento(Double descuento) {
		this.descuento = descuento;
	}

	public byte[] getImagen() {
		return this.imagen;
	}

	public void setImagen(byte[] imagen) {
		this.imagen = imagen;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

	public Set getConsolas() {
		return this.consolas;
	}

	public void setConsolas(Set consolas) {
		this.consolas = consolas;
	}

}
