package Clases;
// Generated 26 mar 2024 17:20:38 by Hibernate Tools 6.3.1.Final

import java.math.BigDecimal;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Juego generated by hbm2java
 */
@Entity
@Table(name="juego")
public class Juego implements java.io.Serializable {
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="id")
	private int id;
	@Column(name="compañia_id")
	private Compannia compannia;
	@Column(name="nombre")
	private String nombre;
	@Column(name="precio")
	private BigDecimal precio;
	@Column(name="anno_de_salida")
	private Date annoDeSalida;
	@Column(name="stock")
	private Integer stock;
	@Column(name="descuento")
	private Double descuento;
	@Column(name="imagen")
	private byte[] imagen;
	@Column(name="genero")
	private String genero;
	@OneToMany(mappedBy="juego", targetEntity=Usuario.class)
	private Set usuarios = new HashSet(0);
	@OneToMany(mappedBy="juego", targetEntity=Consola.class)
	private Set consolas = new HashSet(0);

	public Juego() {
	}

	public Juego(Compannia compannia, String nombre, BigDecimal precio, Date annoDeSalida, Integer stock,
			Double descuento, byte[] imagen, String genero, Set usuarios, Set consolas) {
		this.compannia = compannia;
		this.nombre = nombre;
		this.precio = precio;
		this.annoDeSalida = annoDeSalida;
		this.stock = stock;
		this.descuento = descuento;
		this.imagen = imagen;
		this.genero = genero;
		this.usuarios = usuarios;
		this.consolas = consolas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Compannia getCompannia() {
		return this.compannia;
	}

	public void setCompannia(Compannia compannia) {
		this.compannia = compannia;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public Date getAnnoDeSalida() {
		return this.annoDeSalida;
	}

	public void setAnnoDeSalida(Date annoDeSalida) {
		this.annoDeSalida = annoDeSalida;
	}

	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public Double getDescuento() {
		return this.descuento;
	}

	public void setDescuento(Double descuento) {
		this.descuento = descuento;
	}

	public byte[] getImagen() {
		return this.imagen;
	}

	public void setImagen(byte[] imagen) {
		this.imagen = imagen;
	}

	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

	public Set getConsolas() {
		return this.consolas;
	}

	public void setConsolas(Set consolas) {
		this.consolas = consolas;
	}

}
