package Clases;
// Generated 25 mar 2024 23:14:46 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Permisos generated by hbm2java
 */
public class Permisos implements java.io.Serializable {

	private Integer idpermisos;
	private Byte permisoPublicacion;
	private Byte permisoEliminacion;
	private Byte permisoStock;
	private Byte permisoBaneo;
	private Byte permisoPrecio;
	private Byte permisoDescuento;
	private Set rols = new HashSet(0);

	public Permisos() {
	}

	public Permisos(Byte permisoPublicacion, Byte permisoEliminacion, Byte permisoStock, Byte permisoBaneo,
			Byte permisoPrecio, Byte permisoDescuento, Set rols) {
		this.permisoPublicacion = permisoPublicacion;
		this.permisoEliminacion = permisoEliminacion;
		this.permisoStock = permisoStock;
		this.permisoBaneo = permisoBaneo;
		this.permisoPrecio = permisoPrecio;
		this.permisoDescuento = permisoDescuento;
		this.rols = rols;
	}

	public Integer getIdpermisos() {
		return this.idpermisos;
	}

	public void setIdpermisos(Integer idpermisos) {
		this.idpermisos = idpermisos;
	}

	public Byte getPermisoPublicacion() {
		return this.permisoPublicacion;
	}

	public void setPermisoPublicacion(Byte permisoPublicacion) {
		this.permisoPublicacion = permisoPublicacion;
	}

	public Byte getPermisoEliminacion() {
		return this.permisoEliminacion;
	}

	public void setPermisoEliminacion(Byte permisoEliminacion) {
		this.permisoEliminacion = permisoEliminacion;
	}

	public Byte getPermisoStock() {
		return this.permisoStock;
	}

	public void setPermisoStock(Byte permisoStock) {
		this.permisoStock = permisoStock;
	}

	public Byte getPermisoBaneo() {
		return this.permisoBaneo;
	}

	public void setPermisoBaneo(Byte permisoBaneo) {
		this.permisoBaneo = permisoBaneo;
	}

	public Byte getPermisoPrecio() {
		return this.permisoPrecio;
	}

	public void setPermisoPrecio(Byte permisoPrecio) {
		this.permisoPrecio = permisoPrecio;
	}

	public Byte getPermisoDescuento() {
		return this.permisoDescuento;
	}

	public void setPermisoDescuento(Byte permisoDescuento) {
		this.permisoDescuento = permisoDescuento;
	}

	public Set getRols() {
		return this.rols;
	}

	public void setRols(Set rols) {
		this.rols = rols;
	}

}
