package Clases;
// Generated 25 mar 2024 23:14:46 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Permisos generated by hbm2java
 */
@Entity
@Table(name="permisos")
public class Permisos implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="id_permisos")
	private Integer idpermisos;
	@Column(name="permiso_publicacion")
	private Boolean permisoPublicacion;
	@Column(name="permiso_eliminacion")
	private Boolean permisoEliminacion;
	@Column(name="permiso_stock")
	private Boolean permisoStock;
	@Column(name="permiso_baneo")
	private Boolean permisoBaneo;
	@Column(name="permiso_precio")
	private Boolean permisoPrecio;
	@Column(name="permiso_descuento")
	private Boolean permisoDescuento;
	@OneToMany(mappedBy="permisos", targetEntity=Rol.class)
	private Set rols = new HashSet(0);

	public Permisos() {
	}

	public Permisos(Boolean permisoPublicacion, Boolean permisoEliminacion, Boolean permisoStock, Boolean permisoBaneo,
			Boolean permisoPrecio, Boolean permisoDescuento, Set rols) {
		this.permisoPublicacion = permisoPublicacion;
		this.permisoEliminacion = permisoEliminacion;
		this.permisoStock = permisoStock;
		this.permisoBaneo = permisoBaneo;
		this.permisoPrecio = permisoPrecio;
		this.permisoDescuento = permisoDescuento;
		this.rols = rols;
	}

	public Integer getIdpermisos() {
		return this.idpermisos;
	}

	public void setIdpermisos(Integer idpermisos) {
		this.idpermisos = idpermisos;
	}

	public Boolean getPermisoPublicacion() {
		return this.permisoPublicacion;
	}

	public void setPermisoPublicacion(Boolean permisoPublicacion) {
		this.permisoPublicacion = permisoPublicacion;
	}

	public Boolean getPermisoEliminacion() {
		return this.permisoEliminacion;
	}

	public void setPermisoEliminacion(Boolean permisoEliminacion) {
		this.permisoEliminacion = permisoEliminacion;
	}

	public Boolean getPermisoStock() {
		return this.permisoStock;
	}

	public void setPermisoStock(Boolean permisoStock) {
		this.permisoStock = permisoStock;
	}

	public Boolean getPermisoBaneo() {
		return this.permisoBaneo;
	}

	public void setPermisoBaneo(Boolean permisoBaneo) {
		this.permisoBaneo = permisoBaneo;
	}

	public Boolean getPermisoPrecio() {
		return this.permisoPrecio;
	}

	public void setPermisoPrecio(Boolean permisoPrecio) {
		this.permisoPrecio = permisoPrecio;
	}

	public Boolean getPermisoDescuento() {
		return this.permisoDescuento;
	}

	public void setPermisoDescuento(Boolean permisoDescuento) {
		this.permisoDescuento = permisoDescuento;
	}

	public Set getRols() {
		return this.rols;
	}

	public void setRols(Set rols) {
		this.rols = rols;
	}

}
