package Clases;
// Generated 20 mar 2024 11:35:13 by Hibernate Tools 6.3.1.Final

/**
 * PermisosId generated by hbm2java
 */
public class PermisosId implements java.io.Serializable {

	private int idUsuario;
	private int idpermisos;

	public PermisosId() {
	}

	public PermisosId(int idUsuario, int idpermisos) {
		this.idUsuario = idUsuario;
		this.idpermisos = idpermisos;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public int getIdpermisos() {
		return this.idpermisos;
	}

	public void setIdpermisos(int idpermisos) {
		this.idpermisos = idpermisos;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PermisosId))
			return false;
		PermisosId castOther = (PermisosId) other;

		return (this.getIdUsuario() == castOther.getIdUsuario()) && (this.getIdpermisos() == castOther.getIdpermisos());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUsuario();
		result = 37 * result + this.getIdpermisos();
		return result;
	}

}
