package Clases;
// Generated 20 mar 2024 11:35:13 by Hibernate Tools 6.3.1.Final

import com.github.javafaker.Bool;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Permisos generated by hbm2java
 */
@Entity
@Table(name="permisos")
public class Permisos implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="idpermisos")
	private PermisosId id;
	@Column(name="id_Usuario")
	private Usuario usuario;
	@Column(name="permiso_publicacion")
	private Boolean permisoPublicacion;
	@Column(name="permiso_eliminacion")
	private Boolean permisoEliminacion;
	@Column(name="permiso_stock")
	private Boolean permisoStock;
	@Column(name="permiso_baneo")
	private Boolean permisoBaneo;
	@Column(name="permiso_precio")
	private Boolean permisoPrecio;
	@Column(name="permiso_descuento")
	private Boolean permisoDescuento;

	public Permisos() {
	}

	public Permisos(PermisosId id, Usuario usuario, Boolean permisoPublicacion, Boolean permisoEliminacion, Boolean permisoStock,
			Boolean permisoBaneo, Boolean permisoPrecio, Boolean permisoDescuento) {
		this.id = id;
		this.usuario = usuario;
		this.permisoPublicacion = permisoPublicacion;
		this.permisoEliminacion = permisoEliminacion;
		this.permisoStock = permisoStock;
		this.permisoBaneo = permisoBaneo;
		this.permisoPrecio = permisoPrecio;
		this.permisoDescuento = permisoDescuento;
	}

	public PermisosId getId() {
		return this.id;
	}

	public void setId(PermisosId id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Boolean getPermisoPublicacion() {
		return this.permisoPublicacion;
	}

	public void setPermisoPublicacion(Boolean permisoPublicacion) {
		this.permisoPublicacion = permisoPublicacion;
	}

	public Boolean getPermisoEliminacion() {
		return this.permisoEliminacion;
	}

	public void setPermisoEliminacion(Boolean permisoEliminacion) {
		this.permisoEliminacion = permisoEliminacion;
	}

	public Boolean getPermisoStock() {
		return this.permisoStock;
	}

	public void setPermisoStock(Boolean permisoStock) {
		this.permisoStock = permisoStock;
	}

	public Boolean getPermisoBaneo() {
		return this.permisoBaneo;
	}

	public void setPermisoBaneo(Boolean permisoBaneo) {
		this.permisoBaneo = permisoBaneo;
	}

	public Boolean getPermisoPrecio() {
		return this.permisoPrecio;
	}

	public void setPermisoPrecio(Boolean permisoPrecio) {
		this.permisoPrecio = permisoPrecio;
	}

	public Boolean getPermisoDescuento() {
		return this.permisoDescuento;
	}

	public void setPermisoDescuento(Boolean permisoDescuento) {
		this.permisoDescuento = permisoDescuento;
	}
	
}
