package Clases;
// Generated 25 mar 2024 23:14:46 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol implements java.io.Serializable {

	private int idRol;
	private String nombre;
	private Set permisoses = new HashSet(0);

	public Rol() {
	}

	public Rol(int idRol, String nombre, Set permisoses) {
		this.idRol = idRol;
		this.nombre = nombre;
		this.permisoses = permisoses;
	}

	public int getIdRol() {
		return this.idRol;
	}

	public void setIdRol(int idRol) {
		this.idRol = idRol;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getPermisoses() {
		return this.permisoses;
	}

	public void setPermisoses(Set permisoses) {
		this.permisoses = permisoses;
	}

}
