package Clases;
// Generated 26 mar 2024 17:20:38 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name="rol")
public class Rol implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="id_rol")
	private int idRol;
	@Column(name="nombre")
	private String nombre;
	@OneToMany(mappedBy="rol", targetEntity=Permisos.class)
	private Set permisoses = new HashSet(0);

	public Rol() {
	}

	public Rol(int idRol, String nombre, Set permisoses) {
		this.idRol = idRol;
		this.nombre = nombre;
		this.permisoses = permisoses;
	}

	public int getIdRol() {
		return this.idRol;
	}

	public void setIdRol(int idRol) {
		this.idRol = idRol;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getPermisoses() {
		return this.permisoses;
	}

	public void setPermisoses(Set permisoses) {
		this.permisoses = permisoses;
	}

}
