package Clases;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

// Generated 27 mar 2024 16:53:23 by Hibernate Tools 6.3.1.Final

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name="rol")
public class Rol implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="id_rol")
	private int idRol;
	@Column(name="nombre")
	private String nombre;

	public Rol() {
	}

	public Rol(int idRol, String nombre) {
		this.idRol = idRol;
		this.nombre = nombre;
	}

	public int getIdRol() {
		return this.idRol;
	}

	public void setIdRol(int idRol) {
		this.idRol = idRol;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
