package Clases;
// Generated 20 mar 2024 11:35:13 by Hibernate Tools 6.3.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario")
public class Usuario implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	private Integer id;
	@Column(name = "nombre_usuario")
	private String nombreUsuario;
	@Column(name = "contraseña")
	private String contrasenna;
	@Column(name = "nombre")
	private String nombre;
	@Column(name = "apellidos")
	private String apellidos;
	@Column(name = "domicilio")
	private String domicilio;
	@Column(name = "telefono")
	private String telefono;
	@Column(name = "correo")
	private String correo;
	@Column(name = "fecha_nac")
	private Date fechaNac;
	@OneToMany(mappedBy = "usuario", targetEntity = Permisos.class)
	private Set permisoses = new HashSet(0);
	@OneToMany(mappedBy = "usuario", targetEntity = Juego.class)
	private Set juegos = new HashSet(0);

	public Usuario() {
	}

	public Usuario(String nombreUsuario, String contrasenna, String nombre, String apellidos, String domicilio,
			String telefono, String correo, Date fechaNac, Set permisoses, Set juegos) {
		this.nombreUsuario = nombreUsuario;
		this.contrasenna = contrasenna;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.domicilio = domicilio;
		this.telefono = telefono;
		this.correo = correo;
		this.fechaNac = fechaNac;
		this.permisoses = permisoses;
		this.juegos = juegos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	public String getContrasenna() {
		return this.contrasenna;
	}

	public void setContrasenna(String contrasenna) {
		this.contrasenna = contrasenna;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public Date getFechaNac() {
		return this.fechaNac;
	}

	public void setFechaNac(Date fechaNac) {
		this.fechaNac = fechaNac;
	}

	public Set getPermisoses() {
		return this.permisoses;
	}

	public void setPermisoses(Set permisoses) {
		this.permisoses = permisoses;
	}

	public Set getJuegos() {
		return this.juegos;
	}

	public void setJuegos(Set juegos) {
		this.juegos = juegos;
	}

	public String toString() {
		return "Id: " + this.id + ",Nombre usuario: " + this.nombreUsuario + ",Nombre: " + this.nombre + ",Apellidos: "
				+ this.apellidos + ",Correo: " + this.correo + ",Fecha nacimiento: " + this.fechaNac + ",Domicilio: "
				+ this.domicilio + ",Telefono: " + this.telefono;
	}
}
